name: ResidenceEnhance
version: 1.0.0
main: cn.handyplus.residence.enhance.ResidenceEnhance
api-version: 1.13
author: handy
description: 一款有点好用的领地增强插件
folia-supported: true
depend: [ Residence ]
commands:
  residenceEnhance:
    description: 领地增强插件
    aliases: [ re ]
permissions:
  residenceEnhance.*:
    description: 领地增强插件
    children:
      residenceEnhance.reload: true
  residenceEnhance.reload:
    description: 重新加载配置
    default: op